name: Auto Update News

on:
  schedule:
    - cron: "05 11 * * *"  # Runs at 5:30 AM Kenya Time (2:30 AM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run the news fetcher script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python fetch_news.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add data/news.json
          git diff --staged --quiet || (git commit -m "Updated news data" && git push)

      - name: Trigger Vercel Deployment
        run: curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_rPYjFt3CRZcXPwBIy3tm1CFKmnxX/sOHKgeDBj5"
