name: Update News Daily

on:
  schedule:
    - cron: "45 5 * * *"  # Runs daily at 5:30 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install requests

      - name: Fetch Latest News
        run: |
          mkdir -p data  # Ensure "data" directory exists
          export NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}
          python fetch_news.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "joelmulongo97@gmail.com"
          git add data/news.json
          git commit -m "Updated news data" || echo "No changes to commit"
          git pull --rebase
          git push
